config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    #skip以降の記述によりパスワード変更、管理者登録のルーティングの削除
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admin/registrations",
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    confirmations: "admin/confirmations"
  }

  devise_for :users, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords",
    confirmations: "public/confirmations"
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about', as: 'about'

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    #urlからpublicを消したいためscope moduleを使用
    get '/mypage' => 'users#mypage'
    get '/following' => 'posts#following'
    get '/my_favorites' => 'posts#favorites'
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      get :search, on: :collection
      resource :relationships, only: [:create, :destroy]
  	    get "followings" => "relationships#followings", as: "followings"
  	    get "followers" => "relationships#followers", as: "followers"
    end

    resources :posts do
      get :tags, on: :collection
      resources :comments, only: [:create,:destroy]
      #resourceにするとidがURLに含まれない
      resource :favorite, only: [:create, :destroy]
    end
    #DM機能のルーティング
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show, :index]

  end

  namespace :admin do
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      get :tags, on: :collection
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @keyword = params[:keyword]
    @users = User.where("name LIKE?", "%#{@keyword}%")
    @posts = Post.where("title LIKE?", "%#{@keyword}%")
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/search.html.erb
<div class = "container">
  <div class="h4 pb-2 mb-4 border-bottom border-secondary col-2">
    Search for <%=@keyword %>
  </div>
  <div class = "h5 mb-4 col-2">
    User
  </div>
  <% if @users.present? %>
    <div class = "row">
      <table class = "table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to admin_user_path(user.id) do %>
                <%= image_tag user.get_image.variant( resize: "50x50^", gravity: "center", crop: "50x50+0+0" ) %>
                <%= user.name %>
              <% end %>
            </td>
            <td><%= user.email %></td>
            <td>
              <%= link_to "Edit", edit_admin_user_path(user), class: "btn btn-sm btn-success" %>
              <%= link_to "Delete", admin_user_path(user), method: :delete, class: "btn btn-sm btn-danger" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
  <div class="row">
      <div class="h5 col-5 text-muted">
        The user does not exist
      </div>
    </div>
  <% end %>
  <div class = "h5 mb-4 col-2">
    Post
  </div>
  <% if @posts.present? %>
    <div class = "row">
      <table class = "table">
        <thead>
          <tr>
            <th>Title</th>
            <th></th>
            <th>Creater</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td class="align-middle"><%= link_to admin_post_path(post.id) do %>
                  <%= image_tag post.get_image.variant( resize: "50x50^", gravity: "center", crop: "50x50+0+0" ) %>
                  <%= post.title %>
                <% end %>
            </td>
            <td class="align-middle"><%= audio_tag url_for(post.music), controls: true %>
            </td>
            <td class="align-middle">
              <%= link_to admin_user_path(post.user.id) do %>
                <%= image_tag post.user.get_image.variant( resize: "50x50^", gravity: "center", crop: "50x50+0+0" ) %>
                <%= post.user.name %>
              <% end %>
            </td>
            <td class="align-middle">
              <i class="fa-regular fa-comment"></i>
              <%= post.comments.count %>
            </td>
            <td class="align-middle">
              <%= link_to "Edit", edit_admin_post_path(post),class:"btn btn-sm btn-success" %>
              <%= link_to "Delete", admin_post_path(post), method: :delete, class:"btn btn-sm btn-danger" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
  <div class="row">
      <div class="h5 col-5 text-muted">
        The post does not exist
      </div>
    </div>
  <% end %>
</div>