config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    #skip以降の記述によりパスワード変更、管理者登録のルーティングの削除
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admin/registrations",
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    confirmations: "admin/confirmations"
  }

  devise_for :users, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords",
    confirmations: "public/confirmations"
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about', as: 'about'

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    #urlからpublicを消したいためscope moduleを使用
    get '/mypage' => 'users#mypage'
    get '/following' => 'posts#following'
    get '/my_favorites' => 'posts#favorites'
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      get :search, on: :collection
      resource :relationships, only: [:create, :destroy]
  	    get "followings" => "relationships#followings", as: "followings"
  	    get "followers" => "relationships#followers", as: "followers"
    end

    resources :posts do
      get :tags, on: :collection
      resources :comments, only: [:create,:destroy]
      #resourceにするとidがURLに含まれない
      resource :favorite, only: [:create, :destroy]
    end
    #DM機能のルーティング
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show, :index]

  end

  namespace :admin do
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      get :tags, on: :collection
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  #タグの関連付け
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  validates :name, presence:true, uniqueness: true, length:{maximum:30}
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    if params[:word].present?
      @tags = Tag.where('name LIKE ?', "%#{params[:word]}%").page(params[:page])
    else
      @tags = Tag.page(params[:page])
    end
  end
  
  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/index.html.erb
<div class = "container">
  <div class="h4 pb-2 mb-4 border-bottom border-secondary col-2">
    All tags
  </div>
  <div class="row">
    <div class="d-flex form-group mx-auto">
      <form class ="form-inline">
        <%= form_with url: admin_tags_path, local: true, method: :get do |f| %>
          <%= f.text_field :word, placeholder:"Search by name", required: true, class: "form-control" %>
          <button type="submit" class="btn btn-outline-success"><i class="fa-solid fa-magnifying-glass"></i></button>
        <% end %>
      </form>
      <% if params[:word].present? %>
        <div class="d-flex col-2">
          <%= link_to "Clear", admin_tags_path, class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class = "row">
    <table class = "table col-6 mx-auto">
      <thead>
        <tr>
          <th>tag</th>
          <th>Posts</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
        <tr>
          <td class="align-middle">
            <%= link_to admin_posts_path(tag_id: tag.id) do %>
              <i class="fa-solid fa-tag"></i>
              <%= tag.name %>
            <% end %>
          </td>
          <td class="align-middle">
            <%= tag.posts.count %>
          </td>
          <td class="align-middle">
            <%= link_to "Delete", admin_tag_path(tag), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-3 mx-auto">
    <%= paginate(@tags) %>
  </div>
</div>