config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    #skip以降の記述によりパスワード変更、管理者登録のルーティングの削除
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admin/registrations",
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    confirmations: "admin/confirmations"
  }

  devise_for :users, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords",
    confirmations: "public/confirmations"
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about', as: 'about'

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    #urlからpublicを消したいためscope moduleを使用
    get '/mypage' => 'users#mypage'
    get '/following' => 'posts#following'
    get '/my_favorites' => 'posts#favorites'
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      get :search, on: :collection
      resource :relationships, only: [:create, :destroy]
  	    get "followings" => "relationships#followings", as: "followings"
  	    get "followers" => "relationships#followers", as: "followers"
    end

    resources :posts do
      get :tags, on: :collection
      resources :comments, only: [:create,:destroy]
      #resourceにするとidがURLに含まれない
      resource :favorite, only: [:create, :destroy]
    end
    #DM機能のルーティング
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show, :index]

  end

  namespace :admin do
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      get :tags, on: :collection
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  #ユーザーとの関連付け
  belongs_to :user
  #コメントの関連付け
  has_many :comments, dependent: :destroy
  #いいねとの関連付け
  has_many :favorites, dependent: :destroy
  #タグの関連付け
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  has_one_attached :music
  has_one_attached :image

  validates :title, presence: true
  validates :music, presence: true, blob: { content_type: ['audio/mpeg', 'audio/x-wav', 'audio/flac'] }

  scope :latest, -> {order(created_at: :desc)}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noImage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(tags)
    #タグが存在していれば、タグの名前を配列としてすべて取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    #取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    #送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    #古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    #新しいタグを保存
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name:new_name)
      self.tags << tag
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @post = Post.find(params[:id])
  end

  def index
    if params[:word].present?
      @posts = Post.where('title LIKE ?', "%#{params[:word]}%").page(params[:page])
    elsif params[:tag_id].present?
      @posts = Tag.find(params[:tag_id]).posts
      @posts = Kaminari.paginate_array(@posts).page(params[:page])
    else
      @posts = Post.page(params[:page])
    end
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].split(',')
    if @post.update(post_params)
      @post.save_tags(tag_list)
      flash[:notice] = "Successfully updated!"
      redirect_to admin_post_path(@post)
    else
      flash.now[:alert] = "Failed to update."
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :music)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<div class="container my-5">
  <div class="h4 pb-2 mb-4 border-bottom border-secondary">
    Edit this Post
  </div>
  <%= render "layouts/errors", obj: @post %>
  <%= form_with model: [:admin, @post] do |f| %>
    <div class="form-group col-4">
      <label>Title</label>
      <%= f.text_field :title, autofocus: true, placeholder:"Name this riff", class:"form-control" %>
    </div>
    <div class="form-group col-4">
      <label>Riff</label>
      <%= f.file_field :music, :size => 140, class:"form-control-file" %>
    </div>
    <div class="form-group col-4">
      <label>Image</label>
      <%= f.file_field :image, accept: "image/*", class:"form-control-file" %>
    </div>
    <div class="form-group col-4">
      <label>Body</label>
      <%= f.text_field :body, placeholder:"Describe this riff", class:"form-control" %>
    </div>
    <div class="form-group col-4">
      <label>Tag</label>
      <%= f.text_field :name, class: "form-control", value: @tag_list %>
    </div>
    <div class="col-4">
      <button type="submit" class="btn btn-sm btn-success">Save changes</button>
    </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<div class = "container my-5">
  <div class="h4 pb-2 mb-4 border-bottom border-secondary col-2">
    All riffs
  </div>
  <div class="row">
    <div class="d-flex form-group">
      <form class ="form-inline">
        <%= form_with url: admin_posts_path, local: true, method: :get do |f| %>
          <%= f.text_field :word, placeholder:"Search by title", required: true, class: "form-control" %>
          <button type="submit" class="btn btn-outline-success"><i class="fa-solid fa-magnifying-glass"></i></button>
        <% end %>
      </form>
      <% if params[:word].present? %>
        <div class="d-flex col-2">
          <%= link_to "Clear", admin_posts_path, class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class = "row">
      <table class = "table">
        <thead>
          <tr>
            <th>Title</th>
            <th></th>
            <th></th>
            <th>Creater</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
          <tr>
            <td class="align-middle"><%= link_to admin_post_path(post.id) do %>
                  <%= image_tag post.get_image.variant( resize: "50x50^", gravity: "center", crop: "50x50+0+0" ) %>
                  <%= post.title %>
                <% end %>
            </td>
            <td class="align-middle"><%= audio_tag url_for(post.music), controls: true %>
            </td>
            <td class="align-middle"><%= post.created_at.strftime('%y/%m/%d') %></td>
            <td class="align-middle">
              <%= link_to admin_user_path(post.user.id) do %>
                <%= image_tag post.user.get_image.variant( resize: "50x50^", gravity: "center", crop: "50x50+0+0" ) %>
                <%= post.user.name %>
              <% end %>
            </td>
            <td class="align-middle">
              <i class="fa-regular fa-comment"></i>
              <%= post.comments.count %>
            </td>
            <td class="align-middle">
              <%= link_to "Edit", edit_admin_post_path(post),class:"btn btn-sm btn-success" %>
              <%= link_to "Delete", admin_post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-sm btn-danger" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <div class="mx-auto">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class = "container my-5">
  <div class = "row">
    <div class="col-5">
      <%= image_tag @post.get_image.variant( resize: "400x400^", gravity: "center", crop: "400x400+0+0" ) %>

    </div>

    <div class = "col-7">
      <table class="table">
        <tbody>
          <tr>
            <th>Title</th>
            <th><%= @post.title %></th>
          </tr>
          <tr>
            <th></th>
            <th><%= audio_tag url_for(@post.music), controls: true %></th>
          </tr>
          <tr>
            <th>Body</th>
            <th><%= simple_format(h(@post.body)) %></th>
          </tr>
          <tr>
            <th>Creater</th>
            <th>
              <%= link_to admin_user_path(@post.user.id) do %>
                <%= image_tag @post.user.get_image.variant( resize: "30x30^", gravity: "center", crop: "30x30+0+0" ) %>
                <%= @post.user.name %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <div class="row mx-auto">
        <div>
          <%= link_to "Edit", edit_admin_post_path(@post),class:"btn btn-md btn-success" %>
        </div>
        <div>
          <%= link_to "Delete", admin_post_path(@post), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-md btn-danger pr-2" %>
        </div>
      </div>
      <div class="border-bottom">
        <div class="col-2">
          <i class="fa-regular fa-comment"></i>
          <%= @post.comments.count %> comment
        </div>
        <div>
          <i class="fa-solid fa-tags"></i>
          <% @post.tags.each do |tag| %>
            <%= link_to admin_posts_path(tag_id: tag.id) do %>
              #<%= tag.name %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <% @post.comments.each do |comment| %>
        <div class="col-1">
          <%= image_tag comment.user.get_image.variant( resize: "50x50^", gravity: "center", crop: "50x50+0+0" ) %>
        </div>
        <div class="col-11">
          <strong><%= comment.user.name %></strong>
          at <%= comment.created_at.strftime('%Y/%m/%d') %><br>
          <%= comment.body %>
          <p class="text-right">
            <%= link_to "delete", admin_post_comment_path(comment.post, comment), data: {confirm: "削除しますか？"}, method: :delete %>
          </p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>