config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    #skip以降の記述によりパスワード変更、管理者登録のルーティングの削除
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admin/registrations",
    sessions: "admin/sessions",
    passwords: "admin/passwords",
    confirmations: "admin/confirmations"
  }

  devise_for :users, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "public/registrations",
    sessions: "public/sessions",
    passwords: "public/passwords",
    confirmations: "public/confirmations"
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about', as: 'about'

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    #urlからpublicを消したいためscope moduleを使用
    get '/mypage' => 'users#mypage'
    get '/following' => 'posts#following'
    get '/my_favorites' => 'posts#favorites'
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      get :search, on: :collection
      resource :relationships, only: [:create, :destroy]
  	    get "followings" => "relationships#followings", as: "followings"
  	    get "followers" => "relationships#followers", as: "followers"
    end

    resources :posts do
      get :tags, on: :collection
      resources :comments, only: [:create,:destroy]
      #resourceにするとidがURLに含まれない
      resource :favorite, only: [:create, :destroy]
    end
    #DM機能のルーティング
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show, :index]

  end

  namespace :admin do
    get '/search' => 'searches#search'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:index, :show, :edit, :update, :destroy] do
      get :tags, on: :collection
      resources :comments, only: [:destroy]
    end
    resources :tags, only: [:index, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #ユーザーの関連付け
  belongs_to :user
  #投稿の関連付け
  belongs_to :post
  
  validates :body, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #ユーザーとの関連付け
  belongs_to :user
  #ポストとの関連付け
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  #ユーザーとの関連付け
  belongs_to :user
  #コメントの関連付け
  has_many :comments, dependent: :destroy
  #いいねとの関連付け
  has_many :favorites, dependent: :destroy
  #タグの関連付け
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  has_one_attached :music
  has_one_attached :image

  validates :title, presence: true
  validates :music, presence: true, blob: { content_type: ['audio/mpeg', 'audio/x-wav', 'audio/flac'] }

  scope :latest, -> {order(created_at: :desc)}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noImage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tags(tags)
    #タグが存在していれば、タグの名前を配列としてすべて取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    #取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    #送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    #古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    #新しいタグを保存
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name:new_name)
      self.tags << tag
    end
  end

end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  #タグ の関連付け
  belongs_to :post
  belongs_to :tag
  validates :tag_id, presence: true, uniqueness: { scope: :post_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
  #タグの関連付け
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  validates :name, presence:true, uniqueness: true, length:{maximum:30}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #投稿の関連付け
  has_many :posts, dependent: :destroy
  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :active_relationships, source: :followed
  # フォロワーを取得
  has_many :followers, through: :passive_relationships, source: :follow
  #コメントの関連付け
  has_many :comments, dependent: :destroy
  #いいねとの関連付け
  has_many :favorites, dependent: :destroy
  #DMの関連付け
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, length: { maximum: 50 }


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/noImage.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  # 指定したユーザーをフォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end


  GUEST_USER_EMAIL = "guest@example"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    if params[:word].present?
      @tags = Tag.where('name LIKE ?', "%#{params[:word]}%").page(params[:page])
    else
      @tags = Tag.page(params[:page])
    end
  end
  
  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to admin_tags_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<div>
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <%= obj.errors.count %>件のエラー
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <% if user_signed_in? %>
          <a class="navbar-brand p-3" href="/">
            <% if current_user.email == "guest@example" %>
              <%= link_to posts_path do %>
                <%= image_tag "logo.jpg", size:'80x80'%>
              <% end %>
            <% else %>
              <%= link_to following_path do %>
                <%= image_tag "logo.jpg", size:'80x80'%>
              <% end %>
            <% end %>
          </a>
        <% else %>
          <a class="navbar-brand p-3" href="/">
            <%= link_to root_path do %>
              <%= image_tag "logo.jpg", size:'80x80'%>
            <% end %>
          </a>
        <% end %>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <% if current_user.email == "guest@example" %>
              <li class="nav-item text-center ml-4">
                <%= link_to about_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-circle-question"></i>
                  <p class="d-flex align-items-end">About</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to posts_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-headphones"></i>
                  <p class="d-flex h6 align-items-end">Posts</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-right-from-bracket"></i>
                  <p class="d-flex h6 align-items-end">Sign Out</p>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item form-inline">
                  <%= form_with url: search_path, local: true, method: :get do |f| %>
                    <%= f.text_field :keyword, placeholder:"Search by word", required: true, class: "form-control" %>
                    <button type="submit" class="btn btn-outline-secondary"><i class="fa-solid fa-magnifying-glass"></i></button>
                  <% end %>
              </li>
              <li class="nav-item text-center ml-4">
                <%= link_to about_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-circle-question"></i>
                  <p class="d-flex h6 align-items-end">About</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to mypage_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-house"></i>
                  <p class="d-flex h6 align-items-end">My page</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to users_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-users"></i>
                  <p class="d-flex h6 align-items-end">Users</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to posts_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-headphones"></i>
                  <p class="d-flex h6 align-items-end">Posts</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to rooms_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-message"></i>
                  <p class="d-flex h6 align-items-end">Chats</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to new_post_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-circle-chevron-up"></i>
                  <p class="d-flex h6 align-items-end">Upload</p>
                <% end %>
              </li>
              <li class="nav-item text-center">
                <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-right-from-bracket"></i>
                  <p class="d-flex h6 align-items-end">Sign Out</p>
                <% end %>
              </li>
            <% end %>
          <% elsif admin_signed_in? %>
            <li class="nav-item form-inline">
              <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
                <%= f.text_field :keyword, placeholder:"Search by word", required: true, class: "form-control" %>
                <button type="submit" class="btn btn-outline-secondary"><i class="fa-solid fa-magnifying-glass"></i></button>
              <% end %>
            </li>
            <li class="nav-item text-center ml-4">
              <%= link_to about_path, class:'nav-link text-dark' do %>
                  <i class="fa-solid fa-circle-question"></i>
                  <p class="d-flex h6 align-items-end">About</p>
                <% end %>
            </li>
            <li class="nav-item text-center">
              <%= link_to admin_users_path, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-users"></i>
                <p class="d-flex h6 align-items-end">Users</p>
              <% end %>
            </li>
            <li class="nav-item text-center">
              <%= link_to admin_posts_path, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-headphones"></i>
                <p class="d-flex h6 align-items-end">Posts</p>
              <% end %>
            </li>
            <li class="nav-item text-center">
              <%= link_to admin_tags_path, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-tags"></i>
                <p class="d-flex h6 align-items-end">Tags</p>
              <% end %>
            </li>
            <li class="nav-item text-center">
              <%= link_to destroy_admin_session_path, method: :delete, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-right-from-bracket"></i>
                <p class="d-flex h6 align-items-end">Sign Out</p>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item text-center">
              <%= link_to about_path, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-circle-question"></i>
                <p class="d-flex h6 align-items-end">About</p>
              <% end %>
            </li>
            <li class="nav-item text-center">
              <%= link_to new_user_session_path, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-right-to-bracket"></i>
                <p class="d-flex h6 align-items-end">Sign in</p>
              <% end %>
            </li>
            <li class="nav-item text-center">
              <%= link_to new_user_registration_path, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-user-plus"></i>
                <p class="d-flex h6 align-items-end">Sign up</p>
              <% end %>
            </li>
            <li class="nav-item text-center">
              <%= link_to users_guest_sign_in_path, method: :post, class:'nav-link text-dark' do %>
                <i class="fa-solid fa-user-lock"></i>
                <p class="d-flex h6 align-items-end">Guest in</p>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riff</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/52b496e6c0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <main class="mx-auto">
      <div class='text-success mx-auto my-2 col-7'><%= flash[:notice] %></div>
      <div class='text-danger mx-auto my-2 col-7'><%= flash[:alert] %></div>
      <%= yield %>
    </main>

  </body>
</html>